events {}

http {
    # DNS-сервер Docker всегда находится по этому адресу
    resolver 127.0.0.11 valid=5s;

    server {
        listen 80;

        location / {
            # Мы используем переменную, чтобы Nginx не резолвил имя при старте, 
            # а делал это "на лету"
            set $backend_servers py-service;
            proxy_pass http://$backend_servers:8888;
            
            # Настройки для того, чтобы Nginx не ждал долго ответа от мертвых
            proxy_next_upstream error timeout http_502;
        }
    }
}