---
apiVersion: v1
kind: Service
metadata:
  name: web-service # По этому имени другие поды смогут обращаться к нашему приложению
spec:
  type: ClusterIP   # Внутренний тип сервиса
  selector:
    app: web        # Магия связки: ищет поды с лейблом app: web
  ports:
  - protocol: TCP
    port: 80        # Порт, на котором сервис доступен внутри кластера
    targetPort: 80  # Порт контейнера, куда перенаправлять трафик