#!/bin/bash
set -e

echo "==> 0. Проверка и установка Ansible..."
if ! command -v ansible &> /dev/null; then
    sudo apt-get update && sudo apt-get install -y ansible python3-yaml
fi

echo "==> 1. Создание структуры директорий для роли и шаблонов..."
mkdir -p inventory templates roles/webserver/{defaults,handlers,tasks,templates}

echo "==> 2. Создание файла инвентаря (inventory.ini)..."
cat << 'EOF' > inventory.ini
[webservers]
localhost ansible_connection=local
EOF

echo "==> 3. Создание шаблона балансировщика Nginx..."
cat << 'EOF' > templates/nginx_load_balancer.conf.j2
# Generated by Ansible on {{ ansible_date_time.iso8601 }}
# Target Environment: {{ env | default('development') }}

upstream backend_nodes {
{% for host in groups['webservers'] %}
    # Server Node: {{ host }}
    server {{ hostvars[host]['ansible_host'] | default('127.0.0.1') }}:80 max_fails=3 fail_timeout=30s;
{% endfor %}
}

server {
    listen 80;
    server_name {{ domain_name | default('localhost') }};

    location / {
        proxy_pass http://backend_nodes;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
EOF

echo "==> 4. Создание тестового плейбука для рендеринга Jinja2..."
cat << 'EOF' > test_jinja_render.yml
---
- name: Test Advanced Template Rendering
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    domain_name: "app.example.com"
    env: "production"

  tasks:
    - name: Render dynamic template locally for inspection
      template:
        src: templates/nginx_load_balancer.conf.j2
        dest: /tmp/nginx_load_balancer.conf

    - name: Display rendered template
      command: cat /tmp/nginx_load_balancer.conf
      register: rendered_conf

    - name: Print output
      debug:
        var: rendered_conf.stdout_lines
EOF

echo "==> 5. Наполнение роли 'webserver'..."

cat << 'EOF' > roles/webserver/defaults/main.yml
---
webserver_port: 80
webserver_doc_root: /var/www/html
EOF

cat << 'EOF' > roles/webserver/handlers/main.yml
---
- name: restart webserver
  service:
    name: "{{ webserver_service_name }}"
    state: restarted
EOF

cat << 'EOF' > roles/webserver/tasks/main.yml
---
- name: Set OS-specific package name
  set_fact:
    webserver_service_name: "{{ 'apache2' if ansible_facts['os_family'] == 'Debian' else 'httpd' }}"

- name: Update package cache (Debian)
  apt:
    update_cache: yes
  when: ansible_facts['os_family'] == 'Debian'
  ignore_errors: true

- name: Update package cache (RedHat)
  dnf:
    update_cache: yes
  when: ansible_facts['os_family'] == 'RedHat'
  ignore_errors: true

- name: Install webserver package
  package:
    name: "{{ webserver_service_name }}"
    state: present
  ignore_errors: true

- name: Ensure document root directory exists
  file:
    path: "{{ webserver_doc_root }}"
    state: directory
    mode: '0755'

- name: Deploy index.html template
  template:
    src: index.html.j2
    dest: "{{ webserver_doc_root }}/index.html"
  notify: restart webserver

- name: Ensure webserver service is started and enabled
  service:
    name: "{{ webserver_service_name }}"
    state: started
    enabled: true
  ignore_errors: true
EOF

cat << 'EOF' > roles/webserver/templates/index.html.j2
<h1>Managed by Ansible Role: webserver</h1>
<p>Host: {{ ansible_hostname }}</p>
<p>IP: {{ ansible_default_ipv4.address | default('N/A') }}</p>
EOF

echo "==> 6. Создание корневого плейбука site.yml..."
cat << 'EOF' > site.yml
---
- name: Apply Webserver Role to Web Nodes
  hosts: webservers
  become: true

  roles:
    - role: webserver
      vars:
        webserver_port: 8080
EOF

echo "==> 7. Запуск проверки рендеринга Jinja2 шаблона..."
ansible-playbook -i inventory.ini test_jinja_render.yml

echo "==> 8. Запуск основной роли через site.yml..."
ansible-playbook -i inventory.ini site.yml

echo "==> Готово! Все файлы созданы и успешно отработали."