SELECT 
    first_name, 
    enrollment_date,
    pg_typeof(enrollment_date)
FROM students;

INSERT INTO students (first_name, last_name, email, enrollment_date) 
VALUES ('Dave', 'Miller', 'dave@test.com', '2025-01-01');

-- 1. Создаем последовательность и привязываем её к колонке id
ALTER TABLE students 
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- 2. Синхронизируем счетчик (чтобы он не начал с 1 и не выдал ошибку дубликата)
SELECT setval(pg_get_serial_sequence('students', 'id'), coalesce(max(id), 0) + 1, false) FROM students;