apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-temp
  name: nginx-temp
spec:
  containers:
  - image: nginx:alpine
    name: nginx-temp
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
