name: Terraform

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Select action (apply / destroy)"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy
      environment:
        description: "Environment / Workspace"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  # changed to OIDC
  # ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  # ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  # ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  # Автоматически передаем логин и токен для провайдера docker в Terraform
  # TF_VAR_ghcr_username: ${{ github.actor }}
  # TF_VAR_ghcr_token: ${{ secrets.GHCR_PAT }}
  # Передаем образ по умолчанию
  # TF_VAR_container_image: "ghcr.io/hamka-123/go-web-app:latest"

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: terraform ${{ inputs.action }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./go-web-site/infra

    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
      - name: Save GitHub OIDC token to file
        shell: bash
        run: |
          response="$(
            curl --fail --silent --show-error \
              -H "Authorization: Bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" \
              "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=api%3A%2F%2FAzureADTokenExchange"
          )"

          jq -r '.value' <<< "$response" > github-oidc-token.jwt
      - name: Upload an Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          # Artifact name. If the `archive` input is `false`, the name of the file uploaded will be the artifact name.
          name: github-oidc-token.jwt
          # A file, directory or wildcard pattern that describes what to upload.
          path: terraform_local/github-oidc-token.jwt

      - name: Azure Login via OIDC
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Show Azure Accout info
        run: az account show

      - name: Save Azure access token to file
        shell: bash
        run: |
          az account get-access-token \
            --resource https://management.azure.com/ \
            --query accessToken \
            --output tsv > azure-access-token.jwt

      - name: Upload an Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          # Artifact name. If the `archive` input is `false`, the name of the file uploaded will be the artifact name.
          name: azure-access-token.jwt
          # A file, directory or wildcard pattern that describes what to upload.
          path: ./go-web-site/infra/azure-access-token.jwt

      - name: Terraform Init
        run: terraform init

      - name: Select or Create Workspace
        run: |
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }}

      - name: Terraform Plan
        run: |
          if [ "${{ inputs.action }}" = "destroy" ]; then
            terraform plan -destroy -out=tfplan
          else
            terraform plan -out=tfplan -var="image_tag=${{ github.sha }}"
          fi

      - name: Terraform ${{ inputs.action }}
        run: |
          terraform apply -auto-approve tfplan
